import { Footer } from "@/components/footer";
import { Header } from "@/components/header";
import { routing } from "@/i18n/routing";
import type { Metadata } from "next";
import { hasLocale } from "next-intl";
import { Geist_Mono } from "next/font/google";
import { notFound } from "next/navigation";
import "./globals.css";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body className={`${geistMono.variable} antialiased font-mono`}>
        <div className="max-w-4xl mx-auto px-8 py-8 min-h-screen flex flex-col gap-4">
          <Header />
          <main className="flex flex-auto">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
